version: 2


jobs:
  build:
    machine: true
    working_directory: ~/
    steps:
      - checkout
      
      - run: docker info |
             docker build -t atlantis .

      - run: docker tag atlantis registry.heroku.com/$HEROKU_APP_NAME/web |
             docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com

      - run: docker save -o ~/atlantis.tar registry.heroku.com/$HEROKU_APP_NAME/web

  #placeholder_for_testing

  deploy:
    machine: true
    working_directory: ~/
    steps:
      - run: docker load -i ~/atlantis.tar |
             docker push registry.heroku.com/$HEROKU_APP_NAME/web

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      #- test
      - deploy:
          requires:
            - build