version: 2
jobs:
       build:
              machine: true
              steps:
                     # build image
                     - run: docker info |
                            docker build -t atlantis . |
                            docker tag atlantis registry.heroku.com/$HEROKU_APP_NAME/web |
                            docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com |
                            docker push registry.heroku.com/$HEROKU_APP_NAME/web