version: 2
jobs:
       prepare:
              machine: true
              steps:
                     # build image
                     - run: docker info |
                            docker build -t atlantis .
                     ## deploy the image
       build:
              machine: true
              steps:
                     - run: docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com 8 |
                            docker tag atlantis registry.heroku.com/$HEROKU_APP_NAME/web |
                            docker push registry.heroku.com/$HEROKU_APP_NAME/web