jobs:

  build_and_deploy:
    docker:
      - image: cimg/base:2021.07
    steps:
      # For using docker commands.
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true

      # Build the docker image
      - checkout
      - run: docker build .

      # Deploy to Heroku
      - heroku/install
      - run: heroku container:login
      - heroku/push-docker-image:
          process-types: web
      #- heroku/release-docker-image:
      #    process-types: web

orbs:
  # For using Heroku CLI commandｓ.
  heroku: circleci/heroku@1.2.6

version: 2.1
workflows:
  heroku_deploy:
    jobs:
      - build_and_deploy