version: 2


jobs:
  build:
    docker:
     - image: cimg/base:2021.04

    steps:

      - setup_remote_docker:
          version: 19.03.13

      - checkout
      
      - run: docker info |
             docker build -t atlantis .

      - run: docker tag atlantis registry.heroku.com/$HEROKU_APP_NAME/web |
             docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com

      - run: docker save -o atlantis.tar registry.heroku.com/$HEROKU_APP_NAME/web

      - run: mkdir /tmp/workspace

      - persist_to_workspace:
          root: /tmp/workspace
          paths:
              - atlantis.tar

  #placeholder_for_testing

  deploy:
    docker:
     - image: cimg/base:2021.04

    steps:
      - attach_workspace:
          at: /tmp/workspace

      - setup_remote_docker:
          version: 19.03.13

      - run: docker load -i ~/atlantis.tar |
             docker push registry.heroku.com/$HEROKU_APP_NAME/web

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      #- test
      - deploy:
          requires:
            - build