version: 2


jobs:
  build:
    docker:
     - image: cimg/base:2021.04

    working_directory: /mnt/ramdisk
    steps:

      - setup_remote_docker:
          version: 19.03.13

      - checkout
      
      - run: docker info |
             docker build -t atlantis .

      - run: docker tag atlantis registry.heroku.com/$HEROKU_APP_NAME/web |
             docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com

      - run: docker save -o /mnt/ramdisk/atlantis.tar registry.heroku.com/$HEROKU_APP_NAME/web

  #placeholder_for_testing

  deploy:
    docker:
     - image: cimg/base:2021.04

    working_directory: /mnt/ramdisk
    steps:

      - setup_remote_docker:
          version: 19.03.13

      - run: docker load -i /mnt/ramdisk/atlantis.tar |
             docker push registry.heroku.com/$HEROKU_APP_NAME/web

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      #- test
      - deploy:
          requires:
            - build